import {
  Home,
  BarChart3,
  Clock,
  Grid3X3,
  ChevronRight,
  ChevronLeft,
  ArrowUp,
  ArrowDown,
  RefreshCw,
  Calendar,
  Search,
  Plus,
  X,
  Check,
  Menu,
  LayoutGrid,
  Trash2,
  Pencil,
  MoreHorizontal,
  MoreVertical,
  Wallet,
  CreditCard,
  Banknote,
  HelpCircle,
  UtensilsCrossed,
  Car,
  ShoppingBag,
  Film,
  ShieldCheck,
  Plane,
  Cross,
  Coffee,
  Dumbbell,
  Gift,
  BookOpen,
  PawPrint,
  Gamepad2,
  Bike,
  GraduationCap,
  Brush,
  Leaf,
  Hamburger,
  IceCream,
  Flower2,
  Hammer,
  Heart,
  Users,
  Rocket,
  Shirt,
  Wine,
  Pizza,
  Globe,
  Music,
  Train,
  type LucideIcon
} from 'lucide-react';

interface IconSymbolProps {
  size?: number;
  name: string;
  color?: string;
  className?: string;
}

export function IconSymbol({ size = 24, name, color = '#fff', className = '' }: IconSymbolProps) {
  const iconMap: Record<string, LucideIcon> = {
    'house.fill': Home,
    'chart.bar.fill': BarChart3,
    'clock.fill': Clock,
    'square.grid.2x2': Grid3X3,
    'chevron.right': ChevronRight,
    'chevron.forward': ChevronRight,
    'chevron-forward': ChevronRight,
    'arrow-back': ChevronLeft,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'refresh': RefreshCw,
    'refresh-outline': RefreshCw,
    'calendar': Calendar,
    'calendar-outline': Calendar,
    'search': Search,
    'add': Plus,
    'close': X,
    'checkmark': Check,
    'menu': Menu,
    'apps': LayoutGrid,
    'trash': Trash2,
    'create': Pencil,
    'ellipsis-horizontal': MoreHorizontal,
    'ellipsis-vertical': MoreVertical,
    'wallet': Wallet,
    'card': CreditCard,
    'cash': Banknote,
    'wallet-outline': Wallet,
    'restaurant': UtensilsCrossed,
    'car': Car,
    'bag-handle': ShoppingBag,
    'film': Film,
    'shield-checkmark': ShieldCheck,
    'airplane': Plane,
    'medical': Cross,
    'cafe': Coffee,
    'fitness': Dumbbell,
    'gift': Gift,
    'book': BookOpen,
    'paw': PawPrint,
    'game-controller': Gamepad2,
    'barbell': Dumbbell,
    'bicycle': Bike,
    'school': GraduationCap,
    'brush': Brush,
    'leaf': Leaf,
    'fast-food': Hamburger,
    'ice-cream': IceCream,
    'flower': Flower2,
    'hammer': Hammer,
    'heart': Heart,
    'people': Users,
    'rocket': Rocket,
    'shirt': Shirt,
    'subway': Train,
    'wine': Wine,
    'pizza': Pizza,
    'planet': Globe,
    'musical-notes': Music,
    'grid': Grid3X3,
  };

  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found, using default`);
    return <HelpCircle size={size} color={color} className={className} />;
  }

  return <IconComponent size={size} color={color} className={className} />;
}
